### ISSUE TITLE
About : FileNotFoundError: [Errno 2] No such file or directory: '/home/keyan/User_XiaoMa/amuse/BEAT-cache'

### ISSUE THREAD

**Issue by Mxwgreat** [kiranchhatre/amuse#11]
Hello! This is an excellent project. However, after configuring the environment required for the project, I ran the infer_gesture code directly and found the following error，which seems to be that the BEAT cache file is missing in the project. I look forward to receiving your reply in the future, thank you very much!
Traceback (most recent call last):
  File "main.py", line 268, in <module>
    main(args)
  File "main.py", line 75, in main
    move_lmdbs(old_cache, EXEC_ON_CLUSTER, verbose=True)
  File "/home/keyan/User_XiaoMa/amuse/scripts/utils/misc.py", line 63, in move_lmdbs
    all_caches = list(CACHE_DIR.iterdir())
  File "/home/ma/anaconda3/envs/amuse1/lib/python3.8/pathlib.py", line 1122, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: '/home/keyan/User_XiaoMa/amuse/BEAT-cache'

**Comment by hyunaseo** [comment]
Hi! I have the exactly same issue 🥲 Did you solve it?

**Comment by kiranchhatre** [comment]
Hi, thank you for your interest. Currently, the inference is designed to work with the processed dataset files. You'll need to set up the data files as instructed in the README (https://amuse.is.tue.mpg.de/download.php). Alternatively, you can modify the code to make inferences on specific audio files.

**Comment by kiranchhatre** [comment]
Thanks for reporting this. I recently updated the models on Hugging Face to simplify inference. Please try the latest model files and configuration here: https://huggingface.co/papers/2312.04466
